framework:
    messenger:
        buses:
            setono_sylius_pickup_point.command_bus: ~

jms_serializer:
    metadata:
        directories:
            setono-sylius-pickup-point:
                namespace_prefix: "Setono\\SyliusPickupPointPlugin\\Model"
                path: "@SetonoSyliusPickupPointPlugin/Resources/config/serializer"

flysystem:
    storages:
        setono_sylius_pickup_point.storage.local:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/setono_sylius_pickup_point/data'
